# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "buscemi"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Zac Bowling"]
  s.date = "2012-04-19"
  s.description = "Adds a 'buscemify' shortcut to magickly."
  s.email = "zac@zacbowling.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bookmarklet.js",
    "config.ru",
    "config/staches.yml",
    "mustachio.gemspec",
    "spec/fixtures/vcr_cassettes/big_obama.yml",
    "spec/fixtures/vcr_cassettes/dubya.yml",
    "spec/fixtures/vcr_cassettes/small_obama.yml",
    "spec/spec_helper.rb",
    "spec/support/big_obama.jpeg",
    "spec/support/dubya.jpeg",
    "spec/support/small_obama.jpeg",
    "spec/unit/analyser_spec.rb",
    "spec/unit/job_spec.rb",
    "spec/unit/magickly_spec.rb"
  ]
  s.homepage = "http://github.com/zbowling/buscemiio"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "automatic buscemi-ing of any image"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, ["~> 1.2"])
      s.add_runtime_dependency(%q<dragonfly>, ["~> 0.9"])
      s.add_runtime_dependency(%q<magickly>, ["~> 1.2"])
      s.add_runtime_dependency(%q<addressable>, ["~> 2.2"])
      s.add_runtime_dependency(%q<haml>, ["~> 3.0"])
      s.add_runtime_dependency(%q<face>, ["= 0.0.4"])
      s.add_runtime_dependency(%q<imagesize>, ["~> 0.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5"])
      s.add_development_dependency(%q<webmock>, ["~> 1.8"])
      s.add_development_dependency(%q<vcr>, ["~> 2.0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<linecache19>, ["= 0.5.12"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, ["~> 1.2"])
      s.add_dependency(%q<dragonfly>, ["~> 0.9"])
      s.add_dependency(%q<magickly>, ["~> 1.2"])
      s.add_dependency(%q<addressable>, ["~> 2.2"])
      s.add_dependency(%q<haml>, ["~> 3.0"])
      s.add_dependency(%q<face>, ["= 0.0.4"])
      s.add_dependency(%q<imagesize>, ["~> 0.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.5"])
      s.add_dependency(%q<webmock>, ["~> 1.8"])
      s.add_dependency(%q<vcr>, ["~> 2.0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<linecache19>, ["= 0.5.12"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, ["~> 1.2"])
    s.add_dependency(%q<dragonfly>, ["~> 0.9"])
    s.add_dependency(%q<magickly>, ["~> 1.2"])
    s.add_dependency(%q<addressable>, ["~> 2.2"])
    s.add_dependency(%q<haml>, ["~> 3.0"])
    s.add_dependency(%q<face>, ["= 0.0.4"])
    s.add_dependency(%q<imagesize>, ["~> 0.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.5"])
    s.add_dependency(%q<webmock>, ["~> 1.8"])
    s.add_dependency(%q<vcr>, ["~> 2.0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<linecache19>, ["= 0.5.12"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
  end
end

